# Universal Function

In [1]:
import numpy as np

## 53. Numpy power and square root
<pre>Find the following value in numpy array
1. Power 2 of array([1, 2, 3])
2. Square root of array([4, 9, 16])

Desire Output:
$> [1 4 9]
$> [2. 3. 4.]</pre>

## 54. Negation of numpy boolean array
<pre>Find the negation of array
Given Input:
a = np.array([True, False, True])

Desired Output:
not a: [False  True False]</pre>

In [2]:
a = np.array([True, False, True])


## 55. Element-wise logical operations on two arrays
<pre>Find the logical value of a and b
Given Input:
a = np.array([False, True, False, True])
b = np.array([False, False, True, True])

Desired Output:
a and b: [False False False  True]
a or b: [False  True  True  True]
a xor b: [False  True  True False]</pre>

In [3]:
a = np.array([False, True, False, True])
b = np.array([False, False, True, True])



## 56. Performs unbuffered in place operation on operand
<pre>Make negative the a first and second column, and return a
Given Input:
a = np.array([1, 2, 3, 4])

Desired Output:
array([-1, -2,  3,  4])</pre>

In [15]:
a = np.array([1, 2, 3, 4])


## 57. Performs unbuffered in place operation on operand
<pre>Add items 0 and 1 in a to b, and store results in a
a = np.array([1, 2, 3, 4])
b = np.array([1, 2])

Desired Output:
$> a
array([2, 4, 3, 4])</pre>

In [16]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2])


## 58. Accumulate the result of applying the operator to all elements
<pre>Find the accumulate value by addition and multiplication of a
Given Input:
a = np.array([1, 2, 3])

Desired Output:
array([1, 3, 6])
array([1, 2, 6])
</pre>

In [17]:
a = np.array([1, 2, 3]) # np.add.accumulate() equal np.cumsum()

In [18]:
# multiply.accumulate() 


## 59. Reduces array’s dimension by one, by applying ufunc along one axis.
<pre>Try the folowing 3 function and write down its calcualting logics 
np.multiply.reduce(a)
np.add.reduce(a)
np.power.reduce(a)

Given Input:
a = np.array([2,3,4])

Desired Output:
24
9
4096</pre>

In [8]:
a = np.array([2,3,4]) # = 2*3*4 # = (2**3)**4  ;  use np.power.reduce()


In [9]:
# = 2*3*4


In [10]:
# np.add.reduce() equal to np.sum()


In [11]:
# = (2**3)**4  ;  use np.power.reduce()


## 60. Compute the outer product of two given vectors
<pre>
Given Input:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6]) 

Desired Output:
array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])</pre>

In [26]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6]) # np.multiply.outer() 
print(a*b)

print("np.multiply.outer(a,b):","\n:" ,np.multiply.outer(a,b))

[ 4 10 18]
np.multiply.outer(a,b): 
: [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
# np.multiply.outer()


In [ ]:
# array([ 4, 10, 18])


## 61. First array elements raised to powers from second array
<pre>Use np.float_power(x1, x2) to the positionally-corresponding power
Given Input:
a = np.array([1, 2, 3])
b = np.array([0, 2, 4])

Desired Output:
array([ 1.,  4., 81.])</pre>

In [ ]:
a = np.array([1, 2, 3])
b = np.array([0, 2, 4])

## 62. Returns the element-wise remainder of division
<pre>Find the remainder of division from a b
Given Input:
a = np.array([3, 5, 7])
b = np.array([2, 3, 4])

Desired Output:
array([1, 2, 3])</pre>

In [ ]:
a = np.array([3, 5, 7])
b = np.array([2, 3, 4])

In [ ]:
Array([1, 2, 3]) # The % operator can be used as a shorthand for np.remainder on ndarrays



In [ ]:
# The % operator can be used as a shorthand for np.remainder on ndarrays


## 63. Floor divide
<pre>Return the largest integer smaller or equal to the division of the inputs.
Given Input:
a = np.array([7, 7, 7, 11])
b = np.array([2, 3, 4, 5])

Desired Output:
array([3, 2, 1, 2])</pre>

In [ ]:
a = np.array([7, 7, 7, 11])
b = np.array([2, 3, 4, 5])

## 64. Natural logarithm, element-wise
<pre>
Try Natural logarithm: np.log()
Try Natural logarithm of one plus log(1 + x): np.log1p()

Given Input:
a = np.array([1, 10, np.e])

Desired Output:
array([0.        , 2.30258509, 1.        ])
array([0.69314718, 2.39789527, 1.31326169])</pre>

In [ ]:
a = np.array([1, 10, np.e])

In [ ]:
# array([0.        , 2.30258509, 1.        ])


In [ ]:
# array([0.69314718, 2.39789527, 1.31326169])


## 65. Calculate the exponential of all elements in the input array
<pre>Calculate exp(x)
Calculate exp(x) - 1

Given Input:
a = np.array([1, 10, 100])

Desired Output:
array([2.71828183e+00, 2.20264658e+04, 2.68811714e+43])
array([1.71828183e+00, 2.20254658e+04, 2.68811714e+43])
</pre>

In [ ]:
a = np.array([1, 10, 100])

## 66. Return the non-negative square-root of an array, element-wise.
<pre>Return square root of array
a = np.array([1, 10, 100])</pre>

In [ ]:
a = np.array([1, 10, 100])

## 67. Return the cube-root of an array, element-wise.
<pre>Return cube root of array
a = np.array([1, 8, 1000])</pre>

In [29]:
aaAAaa = np.array([1, 8, 1000])
print(np.power(aaAAaa,1/3))

[ 1.  2. 10.]


## 68. Returns the greatest common divisor

In [30]:
A_GCD=np.gcd(12, 20)
print(A_GCD)

4


In [32]:
AA_GCD=np.gcd.reduce([15, 25, 35])
print(AA_GCD)

5


In [ ]:
np.gcd(np.arange(6), 20)

## 69. Returns the lowest common multiple 

In [ ]:
np.lcm(12, 20)

In [ ]:
np.lcm.reduce([3, 12, 20])

In [33]:
A_LCM=np.lcm.reduce([40, 12, 20])
print(A_LCM)

120


In [ ]:
np.lcm(np.arange(6), 20)

## 70. Test element-wise for NaN and return result as a boolean array

In [35]:
A_SAN=np.isnan([1, 2, np.NaN])


AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

In [ ]:
np.isnan(np.inf)

## 71. Return the ceiling and floor of the input, element-wise.

In [37]:
aa_aa = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])


In [38]:
np.ceil(aa_aa)

array([-1., -1., -0.,  1.,  2.,  2.,  2.])

In [39]:
np.floor(aa_aa)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

## 72. Return the truncated value of the input, element-wise.
The truncated value of the scalar x is the nearest integer i which is closer to zero than x is. In short, the fractional part of the signed number x is discarded.

In [43]:
a_TRU= np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])


In [44]:
np.trunc(a_TRU)

array([-1., -1., -0.,  0.,  1.,  1.,  2.])

In [45]:
np.fix(a_TRU)

array([-1., -1., -0.,  0.,  1.,  1.,  2.])

最大公因數 ( 多個數字 )

In [60]:
a_a = 60  # first number
b_b = 48  # second number

# loop until the remainder is 0
while b_b != 0:
    print("a_a:",a_a)
    print("b_b:",b_b)
    print("a_a % b_b:",a_a % b_b)
    a_a, b_b = b_b, 
    a_a % b_b
    

print(a_a) 

a_a: 60
b_b: 48
a_a % b_b: 12
a_a: 48
b_b: 12
a_a % b_b: 0
12


In [63]:
2%3



2