In [1]:
import numpy as np
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

## 38. Load local data file (no missing data inside)
<pre>Given Input:
local filename: iris.data

Desired Output:
array([(5.1, 3.5, 1.4, 0.2, 'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, 'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, 'Iris-setosa'),
...
       (5.9, 3. , 5.1, 1.8, 'Iris-virginica')],</pre>
dtype=[('sepallength', '<f4'), ('sepalwidth', '<f4'), ('petallength', '<f4'), ('petalwidth', '<f4'), ('species', 'O')])

In [2]:
data = np.loadtxt('iris.data', delimiter=',', dtype={
    'names': ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'),
    'formats': ('f4','f4','f4','f4','object')})

print(data)




[(5.1, 3.5, 1.4, 0.2, 'Iris-setosa') (4.9, 3. , 1.4, 0.2, 'Iris-setosa')
 (4.7, 3.2, 1.3, 0.2, 'Iris-setosa') (4.6, 3.1, 1.5, 0.2, 'Iris-setosa')
 (5. , 3.6, 1.4, 0.2, 'Iris-setosa') (5.4, 3.9, 1.7, 0.4, 'Iris-setosa')
 (4.6, 3.4, 1.4, 0.3, 'Iris-setosa') (5. , 3.4, 1.5, 0.2, 'Iris-setosa')
 (4.4, 2.9, 1.4, 0.2, 'Iris-setosa') (4.9, 3.1, 1.5, 0.1, 'Iris-setosa')
 (5.4, 3.7, 1.5, 0.2, 'Iris-setosa') (4.8, 3.4, 1.6, 0.2, 'Iris-setosa')
 (4.8, 3. , 1.4, 0.1, 'Iris-setosa') (4.3, 3. , 1.1, 0.1, 'Iris-setosa')
 (5.8, 4. , 1.2, 0.2, 'Iris-setosa') (5.7, 4.4, 1.5, 0.4, 'Iris-setosa')
 (5.4, 3.9, 1.3, 0.4, 'Iris-setosa') (5.1, 3.5, 1.4, 0.3, 'Iris-setosa')
 (5.7, 3.8, 1.7, 0.3, 'Iris-setosa') (5.1, 3.8, 1.5, 0.3, 'Iris-setosa')
 (5.4, 3.4, 1.7, 0.2, 'Iris-setosa') (5.1, 3.7, 1.5, 0.4, 'Iris-setosa')
 (4.6, 3.6, 1. , 0.2, 'Iris-setosa') (5.1, 3.3, 1.7, 0.5, 'Iris-setosa')
 (4.8, 3.4, 1.9, 0.2, 'Iris-setosa') (5. , 3. , 1.6, 0.2, 'Iris-setosa')
 (5. , 3.4, 1.6, 0.4, 'Iris-setosa') (5.2, 3.5, 1.5

#### np.loadtxt( ) is equivalent function to np.genfromtxt( ) when no data is missing.

## 39. min, max, standard deviation, mean of numpy array
<pre>Find the max, min, standard deviation, mean of 
'sepallength', 'sepalwidth', 'petallength', and 'petalwidth' respectively.

Given Input:
data = np.loadtxt('iris.data', delimiter=',', dtype={
    'names': ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'),
    'formats': ('f4','f4','f4','f4','object')})
Desired Output:
$> 7.9
$> 2.0
$> 1.7585291
$> 1.1986667
</pre>

In [3]:
sepallength_max=data['sepallength'].max()
sepalwidth_min=data['sepalwidth'].min()
petallength_std=data['petallength'].std()
petallength_mean=data['petallength'].mean()

print(sepallength_max,sepalwidth_min,petallength_std)
print(np.max(data['sepallength']),np.min(data['sepalwidth']),np.std(data['petallength']),petallength_mean)
'''
mu,med,sd=np.mean(sepallength),np.median(sepallength),np.std(sepallength)
print(mu,med,sd)'''

7.9 2.0 1.7585291
7.9 2.0 1.7585291 3.758667


'\nmu,med,sd=np.mean(sepallength),np.median(sepallength),np.std(sepallength)\nprint(mu,med,sd)'

## 40. Sort array by column
<pre>Sort by sepallength 
Given Input:
data = np.loadtxt('iris.data', delimiter=',', dtype={
    'names': ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'),
    'formats': ('f4','f4','f4','f4','object')})

Desired Output:
array([(4.3, 3. , 1.1, 0.1, 'Iris-setosa'),
       (4.4, 3.2, 1.3, 0.2, 'Iris-setosa'),
       (4.4, 3. , 1.3, 0.2, 'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, 'Iris-setosa'),
       (4.5, 2.3, 1.3, 0.3, 'Iris-setosa'),
       (4.6, 3.6, 1. , 0.2, 'Iris-setosa'),
</pre>

In [4]:
#arg_sort
sepallength_argsort=data[np.argsort(data['sepallength'])]
#sepallength_argsort反轉=data[np.argsort(~data['sepallength'])]

sepallength_argsort

#sepallength_argsort反轉



array([(4.3, 3. , 1.1, 0.1, 'Iris-setosa'),
       (4.4, 3.2, 1.3, 0.2, 'Iris-setosa'),
       (4.4, 3. , 1.3, 0.2, 'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, 'Iris-setosa'),
       (4.5, 2.3, 1.3, 0.3, 'Iris-setosa'),
       (4.6, 3.6, 1. , 0.2, 'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, 'Iris-setosa'),
       (4.6, 3.4, 1.4, 0.3, 'Iris-setosa'),
       (4.6, 3.2, 1.4, 0.2, 'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, 'Iris-setosa'),
       (4.7, 3.2, 1.6, 0.2, 'Iris-setosa'),
       (4.8, 3. , 1.4, 0.1, 'Iris-setosa'),
       (4.8, 3. , 1.4, 0.3, 'Iris-setosa'),
       (4.8, 3.4, 1.9, 0.2, 'Iris-setosa'),
       (4.8, 3.4, 1.6, 0.2, 'Iris-setosa'),
       (4.8, 3.1, 1.6, 0.2, 'Iris-setosa'),
       (4.9, 2.4, 3.3, 1. , 'Iris-versicolor'),
       (4.9, 2.5, 4.5, 1.7, 'Iris-virginica'),
       (4.9, 3.1, 1.5, 0.1, 'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, 'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, 'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, 'Iris-setosa'),
       (5. , 3.5, 1.3, 0.

## 41. Find the count number of a condition column
<pre>Find the number of sample that the pentallength greater than its mean.
Given Input:
The previous imported iris data

Desired Output:
$> 93
</pre>

In [5]:
'''
sepallength_max=data['sepallength'].max()
sepalwidth_min=data['sepalwidth'].min()
petallength_std=data['petallength'].std()
petallength_mean=data['petallength'].mean()
'''
pentallength非零=np.count_nonzero(data['petallength']>petallength_mean)

pentallength非零

#result=values[np.where(np.logical_and(values>2 , values<4))]
#A_A_A_5_10=A_A_A[np.where(np.logical_and(A_A_A<=10,A_A_A>=5))]
#np.where(arr3>=3, arr3-1, arr3+1)



93

## 42. Find the mode (most frequent) value in numpy array
<pre>Find the mode of sepalwidth
Given Input:
The previous imported iris data

Desired Output:
$> 3</pre>

In [6]:
vals,counts=np.unique(data['sepalwidth'],return_counts=True )
print("Counts",counts)    # 
print("Vals",vals)        # 位罝
print("Count_max", counts.max())
print("COunt_max",np.argmax(counts))
print("COunt_max_value",vals[np.argmax(counts)])

print(data[counts])


#stats.mode(data['sepalwidth'])
#np.unique 是 NumPy 庫中的一個函數，用於找出陣列中的相同的數值。這個函數可以單純過濾只取唯一值出來，
#也可以選擇性地返回這些唯一值在原始陣列中的中的索引和計數。
'''counter=np.bincount(data['sepalwidth'])
mode=np.argmax(counter)

print("np.bincount(data['sepalwidth']):", counter, "mode=np.argmax(counter)")'''

Counts [ 1  3  4  3  8  5  9 14 10 26 12 13  6 12  6  3  3  6  2  1  1  1  1]
Vals [2.  2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8
 3.9 4.  4.1 4.2 4.4]
Count_max 26
COunt_max 9
COunt_max_value 3.0
[(4.9, 3. , 1.4, 0.2, 'Iris-setosa') (4.6, 3.1, 1.5, 0.2, 'Iris-setosa')
 (5. , 3.6, 1.4, 0.2, 'Iris-setosa') (4.6, 3.1, 1.5, 0.2, 'Iris-setosa')
 (4.4, 2.9, 1.4, 0.2, 'Iris-setosa') (5.4, 3.9, 1.7, 0.4, 'Iris-setosa')
 (4.9, 3.1, 1.5, 0.1, 'Iris-setosa') (5.8, 4. , 1.2, 0.2, 'Iris-setosa')
 (5.4, 3.7, 1.5, 0.2, 'Iris-setosa') (5. , 3.4, 1.6, 0.4, 'Iris-setosa')
 (4.8, 3. , 1.4, 0.1, 'Iris-setosa') (4.3, 3. , 1.1, 0.1, 'Iris-setosa')
 (4.6, 3.4, 1.4, 0.3, 'Iris-setosa') (4.8, 3. , 1.4, 0.1, 'Iris-setosa')
 (4.6, 3.4, 1.4, 0.3, 'Iris-setosa') (4.6, 3.1, 1.5, 0.2, 'Iris-setosa')
 (4.6, 3.1, 1.5, 0.2, 'Iris-setosa') (4.6, 3.4, 1.4, 0.3, 'Iris-setosa')
 (4.7, 3.2, 1.3, 0.2, 'Iris-setosa') (4.9, 3. , 1.4, 0.2, 'Iris-setosa')
 (4.9, 3. , 1.4, 0.2, 'Iris-setosa') (4.9, 3. ,

'counter=np.bincount(data[\'sepalwidth\'])\nmode=np.argmax(counter)\n\nprint("np.bincount(data[\'sepalwidth\']):", counter, "mode=np.argmax(counter)")'

## 43. Shuffle the rows of the dataset
<pre>
Given Input:
data = np.loadtxt('iris.data', delimiter=',', dtype={
    'names': ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'),
    'formats': ('f4','f4','f4','f4','object')})
$> data
array([(5.1, 3.5, 1.4, 0.2, 'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, 'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, 'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, 'Iris-setosa'),
       ....
Desired Output:       
$> data
array([(5.2, 3.4, 1.4, 0.2, 'Iris-setosa'),
       (6. , 2.9, 4.5, 1.5, 'Iris-versicolor'),
       (4.8, 3.1, 1.6, 0.2, 'Iris-setosa'),
       (5.7, 2.8, 4.1, 1.3, 'Iris-versicolor'),
</pre>

In [7]:
data_random=np.random.shuffle(data)
print(data)




[(6. , 3.4, 4.5, 1.6, 'Iris-versicolor')
 (5.4, 3.4, 1.7, 0.2, 'Iris-setosa')
 (6.2, 3.4, 5.4, 2.3, 'Iris-virginica')
 (6.1, 3. , 4.9, 1.8, 'Iris-virginica')
 (7.6, 3. , 6.6, 2.1, 'Iris-virginica')
 (6.6, 3. , 4.4, 1.4, 'Iris-versicolor')
 (5.4, 3.7, 1.5, 0.2, 'Iris-setosa') (5.4, 3.9, 1.7, 0.4, 'Iris-setosa')
 (6.4, 3.2, 4.5, 1.5, 'Iris-versicolor')
 (5.8, 2.6, 4. , 1.2, 'Iris-versicolor')
 (5.4, 3.9, 1.3, 0.4, 'Iris-setosa') (5.1, 3.5, 1.4, 0.2, 'Iris-setosa')
 (5. , 3.3, 1.4, 0.2, 'Iris-setosa')
 (6.7, 3.1, 4.7, 1.5, 'Iris-versicolor')
 (4.9, 3.1, 1.5, 0.1, 'Iris-setosa')
 (6. , 2.2, 4. , 1. , 'Iris-versicolor')
 (6.1, 3. , 4.6, 1.4, 'Iris-versicolor')
 (6.1, 2.9, 4.7, 1.4, 'Iris-versicolor')
 (6.4, 2.9, 4.3, 1.3, 'Iris-versicolor')
 (5.5, 4.2, 1.4, 0.2, 'Iris-setosa')
 (5.4, 3. , 4.5, 1.5, 'Iris-versicolor')
 (5.7, 4.4, 1.5, 0.4, 'Iris-setosa')
 (6.3, 3.4, 5.6, 2.4, 'Iris-virginica')
 (6.7, 3. , 5.2, 2.3, 'Iris-virginica')
 (6.7, 3.1, 4.4, 1.4, 'Iris-versicolor')
 (6.7, 3.3, 5.7, 2

In [8]:
print(data_random)

None


In [9]:
phonebook_111={'ALex':123}
AAA_RRR=np.array(list(phonebook_111.items()))
AAA_RRR

AAA_RRR2=np.array([ [*phonebook_111],[*phonebook_111.values()]
                    ])
print(AAA_RRR2, type(AAA_RRR2))



[['ALex']
 ['123']] <class 'numpy.ndarray'>


## 44. Compute the 10th and 90th percentile of the sepalwidth
<pre>Given Input:
The previous imported iris data

Desired Output:
10th percentile of the sepalwidth:  2.5
90th percentile of the sepalwidth:  3.6099999189376826
</pre>

## 45. Show dataset's shape and dtype
<pre>Given Input:
The previous imported iris data

Desired Output:
(150,)
</pre>
dtype([('sepallength', '<f4'), ('sepalwidth', '<f4'), ('petallength', '<f4'), ('petalwidth', '<f4'), ('species', 'O')])

## 46. Creating a numpy array with an ellipsis
<pre>Access first column of array using ellipsis "..."
Given Input:
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8]])
$> arr
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])   
       
Desired Output:  
[1 5]    
</pre>

## 47. Using broadcasting to perform element-wise operations
<pre>Transpose arr2 and add arr1
Given Input:
arr1 = np.array([[1, 2], [3, 4], [5,6]])
arr2 = np.array([2, 3, 4])

Desired Output:  
array([[ 3,  4],
       [ 6,  7],
       [ 9, 10]])
</pre>

## 48. Using broadcasting to perform element-wise operations
<pre>Transpose arr2 and multiply arr1
Given Input:
arr1 = np.array([[1, 2], [3, 4], [5,6]])
arr2 = np.array([2, 3, 4])

Desired Output:
array([[ 2,  4],
       [ 9, 12],
       [20, 24]])    

## 49. Solve linear algebra
<pre>
Find the value of a and b
1a + 2b = 5
3a + 4b = 6

Desired Output:
[-4.   4.5]
</pre>

In [10]:

x_X=np.array([[1,2],[3,4]])
y_Y=np.array([5,6])

result=np.linalg.solve(x_X,y_Y)
print(result)


[-4.   4.5]


## 50. Solve linear algebra
<pre>Find the value of x y, and z
3x + 4y + 2z = 1
2x + 5y + 3z = 2
x + 2y + z = 3

Desired Output:
[ -5.  12. -16.]</pre>

## 51. Numpy array broadcasting - Scalar multiplication
<pre>Find the broadcasting of a * b
Given Input:
a = np.array([[1, 2], [3, 4]])
b = 2

Desired Output:
[[2 4]
 [6 8]]</pre>

## 51. Numpy array broadcasting - 2D array multiplication
<pre>Find the broadcasting of a * b
Given Input:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([2, 3])

Desired Output:
[[ 2  6]
 [ 6 12]
 [10 18]]

In [6]:
aVa=np.array([[1, 2], [3, 4], [5, 6]])
bVb=np.array([2, 3])
TbVbT=bVb.transpose()

YY=np.array([[1,2,3],[4,5,6]])
YY_TT=YY.transpose()


#aVa_bVb=aVa*bVb)
TbVbT
#print (aVa_bVb)
#print (TbVbT)
print("YY \n",YY)
print("YY_TT:","\n",YY_TT)


YY 
 [[1 2 3]
 [4 5 6]]
YY_TT: 
 [[1 4]
 [2 5]
 [3 6]]


## 52. Numpy array broadcasting - 3D array summation
<pre>Find the broadcasting of a + b
Given Input:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b = np.array([10, 20])

Desired Output:
[[[11 22]
  [13 24]]

 [[15 26]
  [17 28]]]</pre>

In [12]:

A___A = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
B___B = np.array([10, 20])
A___A+B___B

array([[[11, 22],
        [13, 24]],

       [[15, 26],
        [17, 28]]])

In [13]:
(A___A+B___B).shape

(2, 2, 2)

## 53. Numpy power and square root
<pre>Find the following value in numpy array
1. Power 2 of array([1, 2, 3])
2. Square root of array([4, 9, 16])

Desire Output:
$> [1 4 9]
    
$> [2. 3. 4.]</pre>

In [7]:
arr_ay=np.array([4,9,16])
arr_ay_square=np.power(arr_ay,0.5)
arr_ay_square

arr_ay_1=np.array([1,2,3])

arr_ay_power1=np.power(arr_ay_1,2)

print(arr_ay_square)

print(arr_ay_power1)

[2. 3. 4.]
[1 4 9]


## 54. Negation of numpy boolean array
<pre>Find the negation of array
Given Input:
a = np.array([True, False, True])

Desired Output:
not a: [False  True False]</pre>

In [8]:

aaa_aaa = np.array([True, False, True])


AAA_AAA    =np.logical_xor(aaa_aaa, aaa_aaa)
AAA_AAA_not=np.logical_not(aaa_aaa, aaa_aaa)

print("AAA_AAA:\n", AAA_AAA)
print("AAA_AAA_not\n", AAA_AAA_not)


'''
import numpy as np
np.logical_not(3)
False
np.logical_not([True, False, 0, 1])
array([False,  True,  True, False])

'''

#result=values[np.where(np.logical_and(values>2 , values<4))]
#A_A_A_5_10=A_A_A[np.where(np.logical_and(A_A_A<=10,A_A_A>=5))]
#np.where(arr3>=3, arr3-1, arr3+1)



AAA_AAA:
 [False False False]
AAA_AAA_not
 [False  True False]


'\nimport numpy as np\nnp.logical_not(3)\nFalse\nnp.logical_not([True, False, 0, 1])\narray([False,  True,  True, False])\n\n'

## 55. Element-wise logical operations on two arrays
<pre>Find the logical value of a and b
Given Input:
a = np.array([False, True, False, True])
b = np.array([False, False, True, True])

Desired Output:
a and b: [False False False  True]
a or b: [False  True  True  True]
a xor b: [False  True  True False]</pre>


    

In [16]:
aAAa=np.array([False, True, False, True])
bBBb=np.array([False, False, True, True])

aAAa_bBBb=np.logical_and(aAAa,bBBb)
aAAaOobBBb=np.logical_or(aAAa,bBBb)
aAAaμμbBBb=np.logical_xor(aAAa,bBBb)

print(aAAa_bBBb)
print(aAAaOobBBb)
print(aAAaμμbBBb)


[False False False  True]
[False  True  True  True]
[False  True  True False]


## 56. Performs unbuffered in place operation on operand
<pre>Make negative the a first and second column, and return a
Given Input:
a = np.array([1, 2, 3, 4])

Desired Output:
array([-1, -2,  3,  4])</pre>

In [17]:
aÓa=np.array([1, 2, 3, 4])



## 57. Performs unbuffered in place operation on operand
<pre>Add items 0 and 1 in a to b, and store results in a
a = np.array([1, 2, 3, 4])
b = np.array([1, 2])

Desired Output:
$> a
array([2, 4, 3, 4])</pre>


## 58. Accumulate the result of applying the operator to all elements
<pre>Find the accumulate value by addition and multiplication of a
Given Input:
a = np.array([1, 2, 3])

Desired Output:
array([1, 3, 6])
array([1, 2, 6])
</pre>

# np.add.accumulate() equal np.cumsum() array([1, 3, 6]) # multiply.accumulate() 



59. Reduces array’s dimension by one, by applying ufunc along one axis.
Try the folowing 3 function and write down its calcualting logics 
np.multiply.reduce(a)
np.add.reduce(a)
np.power.reduce(a)

Given Input:
a = np.array([2,3,4])

Desired Output:
24
9
409

## 60. Compute the outer product of two given vectors
<pre>
Given Input:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6]) 

Desired Output:
array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])</pre>



a = np.array([1, 2, 3])
b = np.array([4, 5, 6]) # np.multiply.outer() 
ay([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18 
       ]])  # array([ 4, 10, 18])

## 61. First array elements raised to powers from second array
<pre>Use np.float_power(x1, x2) to the positionally-corresponding power
Given Input:
a = np.array([1, 2, 3])
b = np.array([0, 2, 4])

Desired Output:
array([ 1.,  4., 81.])</pre>

a = np.array([1, 2, 3])
b = np.array([0, 2, 4])



## 62. Returns the element-wise remainder of division
<pre>Find the remainder of division from a b
Given Input:
a = np.array([3, 5, 7])
b = np.array([2, 3, 4])

Desired Output:
array([1, 2, 3])</pre> Array([1, 2, 3]) # The % operator can be used as a shorthand for np.remainder on ndarrays






63. Floor divide
Return the largest integer smaller or equal to the division of the inputs.
Given Input:
a = np.array([7, 7, 7, 11])
b = np.array([2, 3, 4, 5])

Desired Output:
array([3, 2, 1, 2]

In [18]:
a = np.array([7, 7, 7, 11])
b = np.array([2, 3, 4, 5])

aOOb=a//b
print(aOOb)
AoooB=np.float_divide(a,b)
print*(AoooB)



[3 2 1 2]


AttributeError: module 'numpy' has no attribute 'float_divide'