In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# NumPy Exercises

## 1. Import numpy as np and print the version number.

In [2]:
import numpy as np
np.__version__

'2.2.4'

## 2. Create a 1D array of numbers from 0 to 9 
$> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 3. Create a 3×3 numpy boolean array of all True’s 
<pre>
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)  </pre>

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## 4. Extract items that satisfy a given condition from 1D array
<pre>
Extract all odd numbers from arr

Given that:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired output:
array([1, 3, 5, 7, 9]) </pre>

In [19]:
# Given Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution


array([1, 3, 5, 7, 9])

## 5. Replace items that satisfy a condition with another value in numpy array
<pre>
Replace all odd numbers in arr with -1

Given Input (in #4):
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:
array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1]) </pre>

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

##  6. Replace items that satisfy a condition without affecting the original array, and use np.where() function, and store value in arr2
<pre>
Replace all odd numbers in arr with -1 without changing arr

Given Input:
arr = np.arange(10)
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:
arr2
array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
</pre>

In [21]:
arr = np.arange(10)


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [22]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 7. Reshape an array
Convert a 1D array to a 2D array with 2 rows
<pre>
Given Input:
np.arange(10)
array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])</pre>

In [23]:
arr = np.arange(10)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
# Setting to -1 automatically decides the number of cols


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 8. Stack two arrays vertically
<pre>
Stack arrays a and b vertically

Given Input:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

Desired Output:
array([[0, 1, 2, 3, 4],
      [5, 6, 7, 8, 9],
      [1, 1, 1, 1, 1],
      [1, 1, 1, 1, 1]])</pre>

In [25]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Method 1:


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
# Method 2:


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## 9. Stack two arrays horizontally
<pre>Stack the arrays a and b horizontally.

Given Input:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

Desired Output:
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
      [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]]) </pre>

In [27]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Method 1:


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [28]:
# Method 2:


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## 10. Generate custom sequences in numpy without hardcoding
<pre>Create the following pattern without hardcoding. 
Use only numpy functions and the below input array arr

Given Input:
arr = np.array([1,2,3])

Desired Output:
array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])</pre>

In [29]:
arr = np.array([1,2,3])


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [30]:
# method 2


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## 11. Get the common items between two python numpy arrays
<pre>
Get the common items between a and b

Given Input:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

Desired Output:
array([2, 4])</pre>

In [31]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])


array([2, 4])

## 12. Remove from one array those items that exist in another
<pre>From array a remove all items present in array b

Given Input:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

Desired Output:
array([1,2,3,4])

In [32]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])



array([1, 2, 3, 4])

In [33]:
np.intersect1d(a,b)

array([5])

In [34]:
np.setdiff1d(b,a)

array([6, 7, 8, 9])

## 13. Get the positions(index) where elements of two arrays match
<pre>Get the positions where elements of a and b match

Given Input:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

Desired Output:
(array([1, 3, 5, 7]),)</pre>

In [35]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# index position


(array([1, 3, 5, 7]),)

## 14. Extract all numbers between a given range from a numpy array
<pre>Get all items between 5 and 10 from a.

Given Input:
a = np.array([2, 6, 1, 9, 10, 3, 27])

Desired Output:
array([6, 9, 10]) 
or
[6, 9, 10]
</pre>

In [36]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

# Method 1


array([ 6,  9, 10])

In [37]:
# Method 2
# [ expression for item in list if conditional ]


[6, 9, 10]

In [38]:
# Method 3
# use lambda


[6, 9, 10]

## 15. Make a python function that handles scalars to work on numpy arrays
<pre>Convert the function maxx that works on two scalars, to work on two arrays.

Given Input:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
$> 5

Desired Output:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
$> array([6, 7, 9, 8, 9, 7, 5])
or
[6, 7, 9, 8, 9, 7, 5]
</pre>

In [49]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

# Method 1  (np.vectorize)


array([6, 7, 9, 8, 9, 7, 5])

In [51]:
# Method 2 (np.frompyfunc)


array([6, 7, 9, 8, 9, 7, 5], dtype=object)

In [40]:
# Method 3 (Lambda)


[6, 7, 9, 8, 9, 7, 5]

## 16. Swap two columns in a 2d numpy array
<pre>Swap columns 0 and 1 in the array arr.

Given Input:
arr = np.arange(9).reshape(3,3)
arr
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Desired Output:       
array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])       
       </pre>

In [41]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

## 17. Swap two rows in a 2d numpy array
<pre>Swap rows 0 and 2 in the array arr:

Given input:
arr = np.arange(9).reshape(3,3)
arr
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
       
Desired Output:
array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])
</pre>

In [43]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

## 18. Reverse the rows of a 2D array
<pre>Reverse the rows of a 2D array arr.
Given Input:
arr = np.arange(12).reshape(4,3)
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Desired Output:
array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])    
</pre>

In [45]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [46]:
# [::]



array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

## 19. Reverse the columns of a 2D array
<pre>Reverse the columns of a 2D array arr.
Given Input:
arr = np.arange(15).reshape(3,5)
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Desired Output:
array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10]])
</pre>

In [47]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10]])