In [9]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [10]:
import numpy as np

## 20. Create a 2D array containing random uniform floats between 5 and 10
<pre>Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10

Desired Output:
array([[5.07634273, 7.32940897, 5.78840303],
       [9.53547942, 7.16008125, 7.67112179],
       [7.42716913, 9.014935  , 9.20378359],
       [6.28776986, 5.7333183 , 6.7932973 ],
       [8.92046486, 7.80469775, 7.51347921]])</pre>

In [11]:
np.random.uniform(5,10, size=(5,3))  # random.uniform(low=0.0, high=1.0, size=None)

array([[9.58 , 5.275, 5.99 ],
       [6.601, 8.97 , 8.559],
       [6.701, 9.561, 8.029],
       [9.24 , 9.666, 7.046],
       [8.761, 7.269, 5.851]])

## - random.normal

In [12]:
np.random.normal(3, 2.5, size=(2, 4))   # np.random.normal(mu, sigma, size)

array([[6.22 , 2.716, 2.992, 2.964],
       [1.513, 3.322, 4.775, 6.739]])

## 21. Print only 3 decimal places in python numpy array
<pre>Print or show only 3 decimal places of the numpy array rand_arr.

Given Input:
rand_arr = np.random.random((2,2))</pre>

In [13]:
rand_arr = np.random.random([2,2])
rand_arr

array([[0.177, 0.099],
       [0.046, 0.269]])

In [14]:
np.set_printoptions(precision=3)
rand_arr

array([[0.177, 0.099],
       [0.046, 0.269]])

In [15]:
np.round(rand_arr,3)

array([[0.177, 0.099],
       [0.046, 0.269]])

In [16]:
np.set_printoptions(precision=8)

## 22. Print a scientific notation (like 1e10) numpy array to standard notation
<pre>Pretty print rand_arr by suppressing the scientific notation (like 1e10)

Given Input:
rand_arr = np.random.random([3,3])/1e3
rand_arr
$> array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],
          [  8.447761e-04,   4.718856e-06,   1.215691e-04],
          [  6.707491e-04,   8.258528e-04,   1.367066e-04]])

Desired Output:
$> array([[ 0.000543,  0.000278,  0.000425],
          [ 0.000845,  0.000005,  0.000122],
          [ 0.000671,  0.000826,  0.000137]])</pre>

In [17]:
1e3

1000.0

In [18]:
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[2.16042591e-04, 4.56351621e-04, 7.62389940e-04],
       [9.11787004e-04, 2.94706680e-04, 4.20623470e-04],
       [8.46391130e-04, 9.37818202e-04, 5.59509274e-05]])

In [19]:
np.set_printoptions(suppress=True, precision=6)  
rand_arr

array([[0.000216, 0.000456, 0.000762],
       [0.000912, 0.000295, 0.000421],
       [0.000846, 0.000938, 0.000056]])

In [20]:
np.set_printoptions(suppress=False)  
rand_arr

array([[2.160426e-04, 4.563516e-04, 7.623899e-04],
       [9.117870e-04, 2.947067e-04, 4.206235e-04],
       [8.463911e-04, 9.378182e-04, 5.595093e-05]])

## 23. Limit the number of items printed in output of numpy array
<pre>Limit the number of items printed in python numpy array a to a maximum of 6 elements.

Given Input:
a = np.arange(15)
$> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Desired Output:
$> array([ 0,  1,  2, ..., 12, 13, 14])
</pre>

In [21]:
np.set_printoptions(suppress=True, edgeitems=3, threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

## 24. Print the full numpy array without truncating
<pre>Print the full numpy array a without truncating.

Given Input:
np.set_printoptions(threshold=6)
a = np.arange(15)
a
$> array([ 0,  1,  2, ..., 12, 13, 14])

Desired Output:
a
$> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])</pre>

In [22]:
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [23]:
np.set_printoptions(threshold=np.Inf)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 25. Import a dataset with numbers and texts keeping the text intact in python numpy
<pre>Import the iris dataset keeping the text intact.
url: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

Desired Output:
array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'),
       ...
</pre>

In [24]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',',  dtype={
    'names': ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'),
    'formats': ('f4','f4','f4','f4','object')})
iris

array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, b'Iris-setosa'),
       (5. , 3.6, 1.4, 0.2, b'Iris-setosa'),
       (5.4, 3.9, 1.7, 0.4, b'Iris-setosa'),
       (4.6, 3.4, 1.4, 0.3, b'Iris-setosa'),
       (5. , 3.4, 1.5, 0.2, b'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, b'Iris-setosa'),
       (5.4, 3.7, 1.5, 0.2, b'Iris-setosa'),
       (4.8, 3.4, 1.6, 0.2, b'Iris-setosa'),
       (4.8, 3. , 1.4, 0.1, b'Iris-setosa'),
       (4.3, 3. , 1.1, 0.1, b'Iris-setosa'),
       (5.8, 4. , 1.2, 0.2, b'Iris-setosa'),
       (5.7, 4.4, 1.5, 0.4, b'Iris-setosa'),
       (5.4, 3.9, 1.3, 0.4, b'Iris-setosa'),
       (5.1, 3.5, 1.4, 0.3, b'Iris-setosa'),
       (5.7, 3.8, 1.7, 0.3, b'Iris-setosa'),
       (5.1, 3.8, 1.5, 0.3, b'Iris-setosa'),
       (5.4, 3.4, 1.7, 0.2, b'Iris-setosa'),
       (5.1, 3.7, 1.5, 0.4, b'Iris-setosa'),
       (4.

## 26. Compute the mean, median, standard deviation of a numpy array
<pre>Find the mean, median, standard deviation of iris's sepallength (1st column)
url: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

Desired Output:
[5.843333333333334, 5.8, 0.8253012917851409]
</pre>

In [25]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [26]:
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print([mu, med, sd])

[5.843333333333334, 5.8, 0.8253012917851409]


## 27. Find the percentile scores of a numpy array
<pre>Find the 5th and 95th percentile of iris's sepallength

Given Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0]) 

Desired Output:
array([4.6  , 7.255])</pre>


In [27]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

np.percentile(sepallength, q=[5, 95])

array([4.6  , 7.255])

## 28. Find the position of missing value in numpy array
<pre>
Find: 
1. Number of missing values
2. Row number that contains missing values
3. The NaN row value

Given Input:
arr = np.array([[1, 2, 3],
                [4, np.NaN, 6],
                [7, 8, 9],
                [np.NaN, np.NaN, np.NaN]
               ])

Desired Output:
Number of missing values: 
 4
Row contains missing values: 
 (array([1, 3]),)
The NaN row: 
 [[ 4. nan  6.]
 [nan nan nan]]</pre>

In [28]:
arr = np.array([[1,2,3],
                [4,np.NaN,6],
                [7,8,9],
                [np.NaN,np.NaN,np.NaN]
               ])
arr

array([[ 1.,  2.,  3.],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.],
       [nan, nan, nan]])

In [29]:
print("Number of missing values: \n", np.isnan(arr).sum())
print("Row contains missing values: \n", 
                      np.where(np.any(np.isnan(arr)==True,axis=1)) )
print("The NaN row: \n",arr[np.where(np.any(np.isnan(arr)==True,axis=1))])

Number of missing values: 
 4
Row contains missing values: 
 (array([1, 3]),)
The NaN row: 
 [[ 4. nan  6.]
 [nan nan nan]]


## 29. Filter with conditions
<pre>
Filter the first column < 9 and fourth column > 4
Given Input:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]
               ])

Desired Output:
$> arr[conditions]
array([[5, 6, 7, 8]])

In [30]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]
               ])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
conditions = (arr[:, 0] < 9) & (arr[:, 3] > 4)

In [32]:
arr[conditions]

array([[5, 6, 7, 8]])

## 30. Inverse set of array
<pre>Multiply the non-NaN array by 2
Given Input:
arr = np.array([[1,2,3],
                [4,np.NaN,6],
                [7,8,9],
                [np.NaN,np.NaN,np.NaN]
               ])
arr[np.any(np.isnan(arr), axis=1)]
$> array([[ 4., nan,  6.],
         [nan, nan, nan]])
         
Desired Output:
array([[ 2.,  4.,  6.],
       [14., 16., 18.]])

In [33]:
arr = np.array([[1,2,3],
                [4,np.NaN,6],
                [7,8,9],
                [np.NaN,np.NaN,np.NaN]
               ])
arr[np.any(np.isnan(arr), axis=1)]

array([[ 4., nan,  6.],
       [nan, nan, nan]])

### ~ means the inverse set of given array

In [34]:
arr[~np.any(np.isnan(arr), axis=1)] * 2

array([[ 2.,  4.,  6.],
       [14., 16., 18.]])

## 31. Drop rows that contain a missing value from a numpy array
<pre>
Given Input:
arr = np.array([[1,2,3],
                [4,np.NaN,6],
                [7,8,9],
                [np.NaN,np.NaN,np.NaN]
               ])
               
Desired Output:
array([[1., 2., 3.],
       [7., 8., 9.]])
</pre>

In [35]:
arr = np.array([[1,2,3],
                [4,np.NaN,6],
                [7,8,9],
                [np.NaN,np.NaN,np.NaN]
               ])

In [36]:
arr = arr[~np.any(np.isnan(arr), axis=1)]
arr

array([[1., 2., 3.],
       [7., 8., 9.]])

## 32. Find the correlation between two numpy array
<pre>
Find the correlation of array a and b
Given Input:
a = np.array([1, 2, 3, 4, 5.5])
b = np.array([6, 7, 8, 9, 10.1])

Desired Output:
array([[1.        , 0.99747669],
       [0.99747669, 1.        ]])</pre>


In [37]:
a = np.array([1, 2, 3, 4, 5.5])
b = np.array([6, 7, 8, 9, 10.1])

In [38]:
np.corrcoef(a, b)

array([[1.      , 0.997477],
       [0.997477, 1.      ]])

## 33. Count NaN and non-NaN in numpy array
<pre> 
Given Input:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])
arr
$> array([ 0.,  1.,  2.,  3., nan,  5., nan, nan])

Desired Output:
$> There are 5 non-NaN.
$> There are 3 NaN.</pre> 


In [39]:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])
arr

array([ 0.,  1.,  2.,  3., nan,  5., nan, nan])

In [40]:
print(f"There are {np.count_nonzero(~np.isnan(arr))} non-NaN.")

There are 5 non-NaN.


In [41]:
print(f"There are {np.count_nonzero(np.isnan(arr))} NaN.")

There are 3 NaN.


## 34. Replace all missing values with 0 in a numpy array
<pre>Given Input:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])
arr
$> array([ 0.,  1.,  2.,  3., nan,  5., nan, nan])

Desired Output:
$> array([0., 1., 2., 3., 0., 5., 0., 0.])
</pre> 

In [42]:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])
arr

array([ 0.,  1.,  2.,  3., nan,  5., nan, nan])

In [43]:
arr[np.isnan(arr)] = 0
arr

array([0., 1., 2., 3., 0., 5., 0., 0.])

## 35. Replace all missing values with mean in a numpy array
<pre>Given Input:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])

Desired Output:
$> arr
array([0. , 1. , 2. , 3. , 2.2, 5. , 2.2, 2.2])</pre>

In [44]:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])
arr

array([ 0.,  1.,  2.,  3., nan,  5., nan, nan])

In [45]:
arr[np.isnan(arr)] = np.mean(arr[~np.isnan(arr)])
arr

array([0. , 1. , 2. , 3. , 2.2, 5. , 2.2, 2.2])

## 36. Find the count of unique values in a numpy array
<pre>Given Input:
$> stud_gender = ['Male','Male','Female','Male','Female','Female','Female']
$> stud_gender
['Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Female']

Desired Output:</pre>
(array(['Female', 'Male'], dtype='<U6'), array([4, 3]))

In [46]:
stud_gender = ['Male','Male','Female','Male','Female','Female','Female']
stud_gender

['Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Female']

In [47]:
np.unique(stud_gender)

array(['Female', 'Male'], dtype='<U6')

In [48]:
np.unique(stud_gender, return_counts=True)

(array(['Female', 'Male'], dtype='<U6'), array([4, 3]))

## 37. Convert numeric value to categoric value
<pre>Given Input:
$> stud_result = np.random.randint(0, 100, size=50)
$> stud_result
array([ 9, 86,  6, 67, 14, 64, 18, 83,  5, 66, 15, 68, 66, 58,  1, 64,  8,
       64, 97, 12, 45, 12,  1,  0, 21, 75, 12, 15, 46, 76, 50, 21,  2, 31,
        5, 54, 91, 48, 10, 89, 52, 61, 52, 85, 40, 28,  3, 29, 20, 40])

Desired Output:
Categorize the reult in 'Fail':below 50, 'Pass':blow 70, 'Good':below 100'
</pre>

In [49]:
stud_result = np.random.randint(0, 101, size=50)
stud_result

array([ 68,  54,  54,  59,  56,  92,  73,  93,  25,  18,   9,  90,  64,
        74,  43,  82,  11,  74, 100,  57,  41,  80,   8,  25,  40,   5,
        79,  57,  45,  58,  75,  35,   9,  31,  23,  24,  70,  63,  11,
        65,   9,  89,  56,  45,  91,  11,  21,  14,  92,  24])

In [50]:
# digitize the result in to 4 ranges 
# https://numpy.org/doc/stable/reference/generated/numpy.digitize.html
cat = np.digitize(stud_result, np.array([0, 50, 70, 101]), right = False)
cat

array([2, 2, 2, 2, 2, 3, 3, 3, 1, 1, 1, 3, 2, 3, 1, 3, 1, 3, 3, 2, 1, 3,
       1, 1, 1, 1, 3, 2, 1, 2, 3, 1, 1, 1, 1, 1, 3, 2, 1, 2, 1, 3, 2, 1,
       3, 1, 1, 1, 3, 1])

In [51]:
cat_label = {1:'Fail', 2:'Pass', 3:'Good'}

In [52]:
result_in_cat = [cat_label[x] for x in cat]
result_in_cat

['Pass',
 'Pass',
 'Pass',
 'Pass',
 'Pass',
 'Good',
 'Good',
 'Good',
 'Fail',
 'Fail',
 'Fail',
 'Good',
 'Pass',
 'Good',
 'Fail',
 'Good',
 'Fail',
 'Good',
 'Good',
 'Pass',
 'Fail',
 'Good',
 'Fail',
 'Fail',
 'Fail',
 'Fail',
 'Good',
 'Pass',
 'Fail',
 'Pass',
 'Good',
 'Fail',
 'Fail',
 'Fail',
 'Fail',
 'Fail',
 'Good',
 'Pass',
 'Fail',
 'Pass',
 'Fail',
 'Good',
 'Pass',
 'Fail',
 'Good',
 'Fail',
 'Fail',
 'Fail',
 'Good',
 'Fail']

In [53]:
# Cross check
dict(zip(stud_result, result_in_cat))

{68: 'Pass',
 54: 'Pass',
 59: 'Pass',
 56: 'Pass',
 92: 'Good',
 73: 'Good',
 93: 'Good',
 25: 'Fail',
 18: 'Fail',
 9: 'Fail',
 90: 'Good',
 64: 'Pass',
 74: 'Good',
 43: 'Fail',
 82: 'Good',
 11: 'Fail',
 100: 'Good',
 57: 'Pass',
 41: 'Fail',
 80: 'Good',
 8: 'Fail',
 40: 'Fail',
 5: 'Fail',
 79: 'Good',
 45: 'Fail',
 58: 'Pass',
 75: 'Good',
 35: 'Fail',
 31: 'Fail',
 23: 'Fail',
 24: 'Fail',
 70: 'Good',
 63: 'Pass',
 65: 'Pass',
 89: 'Good',
 91: 'Good',
 21: 'Fail',
 14: 'Fail'}

In [54]:
x = np.array([1.2, 10.0, 12.4, 15.5, 20.])
bins = np.array([0, 5, 10, 15, 20])
np.digitize(x, bins, right=True)

array([1, 2, 3, 4, 4])

In [55]:
np.digitize(x, bins, right=False)

array([1, 3, 3, 4, 5])

In [56]:
[ ( str(x)+'-Good'
       if x > 70
    else
        str(x)+'-Pass')
            if x >= 50
                else
                    str(x)+'-Fail'
            for x in stud_result
]

['68-Pass',
 '54-Pass',
 '54-Pass',
 '59-Pass',
 '56-Pass',
 '92-Good',
 '73-Good',
 '93-Good',
 '25-Fail',
 '18-Fail',
 '9-Fail',
 '90-Good',
 '64-Pass',
 '74-Good',
 '43-Fail',
 '82-Good',
 '11-Fail',
 '74-Good',
 '100-Good',
 '57-Pass',
 '41-Fail',
 '80-Good',
 '8-Fail',
 '25-Fail',
 '40-Fail',
 '5-Fail',
 '79-Good',
 '57-Pass',
 '45-Fail',
 '58-Pass',
 '75-Good',
 '35-Fail',
 '9-Fail',
 '31-Fail',
 '23-Fail',
 '24-Fail',
 '70-Pass',
 '63-Pass',
 '11-Fail',
 '65-Pass',
 '9-Fail',
 '89-Good',
 '56-Pass',
 '45-Fail',
 '91-Good',
 '11-Fail',
 '21-Fail',
 '14-Fail',
 '92-Good',
 '24-Fail']