In [11]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [12]:
import numpy as np

## 20. Create a 2D array containing random floats between 5 and 10
<pre>Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10

Desired Output:
array([[5.07634273, 7.32940897, 5.78840303],
       [9.53547942, 7.16008125, 7.67112179],
       [7.42716913, 9.014935  , 9.20378359],
       [6.28776986, 5.7333183 , 6.7932973 ],
       [8.92046486, 7.80469775, 7.51347921]])</pre>

## 21. Print only 3 decimal places in python numpy array
<pre>Print or show only 3 decimal places of the numpy array rand_arr.

Given Input:
rand_arr = np.random.random((2,2))</pre>

In [13]:
rand_arr = np.random.random([2,2])
rand_arr

array([[0.70010045, 0.7846321 ],
       [0.0012322 , 0.30006001]])

## 22. Print a scientific notation (like 1e10) numpy array to standard notation
<pre>Pretty print rand_arr by suppressing the scientific notation (like 1e10)

Given Input:
rand_arr = np.random.random([3,3])/1e3
rand_arr
$> array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],
          [  8.447761e-04,   4.718856e-06,   1.215691e-04],
          [  6.707491e-04,   8.258528e-04,   1.367066e-04]])

Desired Output:
$> array([[ 0.000543,  0.000278,  0.000425],
          [ 0.000845,  0.000005,  0.000122],
          [ 0.000671,  0.000826,  0.000137]])</pre>

In [14]:
1e3

1000.0

In [15]:
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[0.00040149, 0.00050214, 0.00060266],
       [0.00081438, 0.00048813, 0.00059979],
       [0.00042991, 0.00035629, 0.0007995 ]], shape=(3, 3))

## 23. Limit the number of items printed in output of numpy array
<pre>Limit the number of items printed in python numpy array a to a maximum of 6 elements.

Given Input:
a = np.arange(15)
$> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Desired Output:
$> array([ 0,  1,  2, ..., 12, 13, 14])
</pre>

In [16]:

a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14], shape=(15,))

## 24. Print the full numpy array without truncating
<pre>Print the full numpy array a without truncating.

Given Input:
np.set_printoptions(threshold=6)
a = np.arange(15)
a
$> array([ 0,  1,  2, ..., 12, 13, 14])

Desired Output:
a
$> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])</pre>

In [17]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14], shape=(15,))

## 25. Import a dataset with numbers and texts keeping the text intact in python numpy
<pre>Import the iris dataset keeping the text intact.
url: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

Desired Output:
array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'),
       ...
</pre>

## 26. Compute the mean, median, standard deviation of a numpy array
<pre>Find the mean, median, standard deviation of iris's sepallength (1st column)
url: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

Desired Output:
[5.843333333333334, 5.8, 0.8253012917851409]
</pre>

In [18]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

NameError: name 'url' is not defined

## 27. Find the percentile scores of a numpy array
<pre>Find the 5th and 95th percentile of iris's sepallength

Given Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0]) 

Desired Output:
array([4.6  , 7.255])</pre>


In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])



## 28. Find the position of missing value in numpy array
<pre>
Find: 
1. Number of missing values
2. Row number that contains missing values
3. The NaN row value

Given Input:
arr = np.array([[1, 2, 3],
                [4, np.NaN, 6],
                [7, 8, 9],
                [np.NaN, np.NaN, np.NaN]
               ])

Desired Output:
Number of missing values: 
 4
Row contains missing values: 
 (array([1, 3]),)
The NaN row: 
 [[ 4. nan  6.]
 [nan nan nan]]</pre>

In [ ]:
arr = np.array([[1,2,3],
                [4,np.NaN,6],
                [7,8,9],
                [np.NaN,np.NaN,np.NaN]
               ])
arr

In [ ]:
print("Number of missing values: \n",)
print("Row contains missing values: \n",  )
print("The NaN row: \n",)

## 29. Filter with conditions
<pre>
Filter the first column < 9 and fourth column > 4
Given Input:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]
               ])

Desired Output:
$> arr[conditions]
array([[5, 6, 7, 8]])

In [ ]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]
               ])
arr

In [ ]:
conditions = '?'

In [ ]:
arr[conditions]

## 30. Inverse set of array
<pre>Multiply the non-NaN array by 2
Given Input:
arr = np.array([[1,2,3],
                [4,np.NaN,6],
                [7,8,9],
                [np.NaN,np.NaN,np.NaN]
               ])
arr[np.any(np.isnan(arr), axis=1)]
$> array([[ 4., nan,  6.],
         [nan, nan, nan]])
         
Desired Output:
array([[ 2.,  4.,  6.],
       [14., 16., 18.]])

In [ ]:
arr = np.array([[1,2,3],
                [4,np.NaN,6],
                [7,8,9],
                [np.NaN,np.NaN,np.NaN]
               ])
arr[np.any(np.isnan(arr), axis=1)]

### ~ means the inverse set of given array

## 31. Drop rows that contain a missing value from a numpy array
<pre>
Given Input:
arr = np.array([[1,2,3],
                [4,np.NaN,6],
                [7,8,9],
                [np.NaN,np.NaN,np.NaN]
               ])
               
Desired Output:
array([[1., 2., 3.],
       [7., 8., 9.]])
</pre>

In [ ]:
arr = np.array([[1,2,3],
                [4,np.NaN,6],
                [7,8,9],
                [np.NaN,np.NaN,np.NaN]
               ])

## 32. Find the correlation coefficient between two numpy array
<pre>
Find the correlation of array a and b
Given Input:
a = np.array([1, 2, 3, 4, 5.5])
b = np.array([6, 7, 8, 9, 10.1])

Desired Output:
$> array([[1.        , 0.99747669],
       [0.99747669, 1.        ]])</pre>


In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5.5])
b = np.array([6, 7, 8, 9, 10.1])

In [ ]:
# Find the correlation between a and b


## 33. Count NaN and non-NaN in numpy array
<pre> 
Given Input:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])
arr
$> array([ 0.,  1.,  2.,  3., nan,  5., nan, nan])

Desired Output:
$> There are 5 non-NaN.
$> There are 3 NaN.</pre> 


In [ ]:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])
arr

In [ ]:
print(f"There are ??? non-NaN.")

In [ ]:
print(f"There are ??? NaN.")

## 34. Replace all missing values with 0 in a numpy array
<pre>Given Input:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])
arr
$> array([ 0.,  1.,  2.,  3., nan,  5., nan, nan])

Desired Output:
$> array([0., 1., 2., 3., 0., 5., 0., 0.])
</pre> 

In [ ]:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])
arr

## 35. Replace all missing values with mean in a numpy array
<pre>Given Input:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])

Desired Output:
$> arr
array([0. , 1. , 2. , 3. , 2.2, 5. , 2.2, 2.2])</pre>

In [ ]:
arr = np.array([0, 1, 2, 3, np.NaN, 5, np.NaN, np.NaN])
arr

## 36. Find the count of unique values in a numpy array
<pre>Given Input:
$> stud_gender = ['Male','Male','Female','Male','Female','Female','Female']
$> stud_gender
['Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Female']

Desired Output:</pre>
(array(['Female', 'Male'], dtype='<U6'), array([4, 3]))

In [ ]:
stud_gender = ['Male','Male','Female','Male','Female','Female','Female']
stud_gender

In [ ]:
np.unique(stud_gender)

## 37. Convert numeric value to categoric value
<pre>Given Input:
$> stud_result = np.random.randint(0, 100, size=50)
$> stud_result
array([ 9, 86,  6, 67, 14, 64, 18, 83,  5, 66, 15, 68, 66, 58,  1, 64,  8,
       64, 97, 12, 45, 12,  1,  0, 21, 75, 12, 15, 46, 76, 50, 21,  2, 31,
        5, 54, 91, 48, 10, 89, 52, 61, 52, 85, 40, 28,  3, 29, 20, 40])

Desired Output:
Categorize the reult in 'Fail':below 50, 'Pass':blow 70, 'Good':below 100'
['Fail',
 'Good',
 'Fail',
 'Pass',
 'Fail',
 'Pass',
 'Fail',
 'Fail',
 'Fail',
 'Fail',
 'Good',
 'Good',
 'Pass',
 'Fail',
 'Pass',
 'Fail',
 'Pass',
 'Good',
 'Pass',
 'Pass',
 'Fail',
 'Good',
 'Pass',
 'Pass',
 'Pass',
 'Fail',
 'Good',
 'Fail',
 'Pass',
 'Fail',
 'Pass',
 'Fail',
 'Good',
 'Fail',
 'Fail',
 'Pass',
 'Pass',
 'Fail',
 'Fail',
 'Pass',
 'Fail',
 'Fail',
 'Good',
 'Fail',
 'Good',
 'Fail',
 'Fail',
 'Good',
 'Fail',
 'Pass']
</pre>

In [ ]:
stud_result = np.random.randint(0, 100, size=50)
stud_result

In [ ]:
# digitize the result in to 4 ranges 


In [ ]:
cat_label = {1:'Fail', 2:'Pass', 3:'Good'}